/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* export const projectId = "wvictafepzzrchiywxpk"
/* export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aWN0YWZlcHp6cmNoaXl3eHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NDgzOTgsImV4cCI6MjA4MDMyNDM5OH0.3YKw4ppkyN-CCBJUgInmEUNMfl9PZ8nGLtxSHzQ1m2c"

export const projectId = "" // not used for self-hosted
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzM1Njg5NjAwLCJleHAiOjE4OTM0NTYwMDB9.GAZUJxCaADk4u0hNJBE_k_lG3fqbzKravFRj6irq7co"
